#
# Basic version of stack, for Github
#
services:
  # An instance of RedPanda Schema Registry
  # To run it as a standalone container:
  #   docker network create redpanda-network
  #   docker volume create redpanda-volume
  #   docker run --name=schema_registry --net=redpanda-network -v "redpanda-volume:/var/lib/redpanda/data" -p 8081:8081 \
  #      docker.redpanda.com/redpandadata/redpanda:latest redpanda start --mode dev-container --smp 1 --memory 500M
  schema_registry:
    command:
      - redpanda
      - start
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --memory 500M
    image: docker.redpanda.com/redpandadata/redpanda:${REDPANDA_VERSION:-latest}
    volumes:
      - redpanda-volume:/var/lib/redpanda/data
    networks:
      - redpanda-network
    ports:
      - 8081:8081

  rabbitmq:
    image: rabbitmq:3-management
    hostname: heron-rabbitmq
    ports:
      - "5672:5672"
      - "8080:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq-volume:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: development

volumes:
  redpanda-volume:
  rabbitmq-volume:

networks:
  external:
  redpanda-network:
