name: CI

on:
  push:
    branches:
      - develop-*
      - develop
      - master
  pull_request:
    branches:
      - develop-*
      - develop
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          python -m black --check .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          flake8
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          python -m mypy .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          python -m pytest -vx --cov=.

