name: CI

on:
  push:
    branches:
      - master
      - '143-write-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Create rst files for docs
        run: |
          pip install sphinx
          pip install sphinx-autodoc-typehints
          pip install sphinx-pdj-theme
          mkdir doc
          sphinx-apidoc -o docs/source/ tol_lab_share tol_lab_share/config tol_lab_share/constants setup_dev_rabbit.py
          make html -C docs
          cp -r docs/build/html/* doc/

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc

  deploy:
    runs-on: ubuntu-latest
    needs: build  # The deploy job will only run if the build job is successful

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
          
          
